// HV here referred as HOME VIDEOS
export const VIDEOS_REQUEST='VIDEOS_REQUEST';
export const VIDEOS_SUCCESS='VIDEOS_SUCCESS';
export const VIDEOS_FAILED='VIDEOS_FAILED';


export const VIDEO_SELECTED_REQUEST='VIDEO_SELECTED_REQUEST';
export const VIDEO_SELECTED_SUCCESS='VIDEO_SELECTED_SUCCESS';
export const VIDEO_SELECTED_FAILED='VIDEO_SELECTED_FAILED';